[package]
name = "video_cration_llm_manim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.30"
langchain-rust = "3.2.2"
serde = "1.0.197"
serde_json = "1.0.115"
tokio = "1.37.0"
